---
- hosts: ubuntu
  become: true
  
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present


    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Log into artifactory registry
      docker_login:
        registry: juanestebangorillatest-test.jfrog.io
        username: admin
        password: Adminjuanes!
        reauthorize: yes

    - name: pull the image
      docker_image:
        name: juanestebangorillatest-test.jfrog.io/timeoff
        source: pull

    - name: Create the container
      docker_container:
        name: alpine_timeoff
        image: juanestebangorillatest-test.jfrog.io/timeoff
        state: started
        recreate: yes
        ports: 3000:3000
